[package]
name = "numfmt-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
winnow = "0.7.13"
bitflags = "2.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
num-bigint = "0.4"
num-traits = "0.2"
